#!/bin/bash
set -e

remove-rpath-dups() {
    local paths=($(echo "$1" |tr : ' '))
    local retval=()
    local seen; declare -A seen
    for path in "${paths[@]}"; do
        if [ "${seen[$path]}" = "" ]; then
            seen[$path]=yes
            retval=("${retval[@]}" "$path")
        fi
    done
    echo "${retval[@]}" |tr ' ' :
}

add="$1"
exe="$2"

rpath="$(patchelf --print-rpath "$exe")"
old_rpath="$rpath"

if [ -n "$rpath" ]; then
    if [ -n "$add" ]; then
	rpath="$rpath:$add"
    fi
else
    if [ -n "$add" ]; then
	rpath="$add"
    fi
fi

if [ "$rpath" != "$old_rpath" ]; then
    rpath="$(remove-rpath-dups "$rpath")"
    patchelf --set-rpath "$rpath" "$exe"
fi
